### ISSUE TITLE
A torrent with videos

### ISSUE THREAD

**Issue by mgrankin** [sangho-vision/acav100m#2]
Hey,

It would be great if you make a torrent with a dataset. Thanks!

**Comment by JiwanChung** [comment]
Sadly, we cannot share raw videos since we do not own copyrights to the YouTube videos themselves.
Academic Torrents requires that the uploader bears the copyright to the files, which we do not.

> User Uploads
> All files uploaded to Academic Torrents must be legal to share. By posting a file to the site you assign the minimum amount of rights or certify that we have the minimum amount of rights needed to host it.

https://academictorrents.com/terms.php#uploads
